language: swift
osx_image: xcode10.2
xcode_project: ElasticSwift.xcodeproj
xcode_scheme: ElasticSwiftTests
before_install:
  - brew update >/dev/null
  - brew cask install homebrew/cask-versions/adoptopenjdk8
  - brew install elasticsearch
  - brew services start elasticsearch
before_script:
  - sleep 10
script:
  - swift build
  - swift test
after_success:
  - xcodebuild -quiet -scheme ElasticSwift-Package build test
  - bash <(curl -s https://codecov.io/bash) -J 'ElasticSwift' -J 'ElasticSwiftCore' -J 'ElasticSwiftCodableUtils' -J 'ElasticSwiftNetworking' -J 'ElasticSwiftQueryDSL'
